### ISSUE TITLE
Bleeding `dim` and `bold` inside nested calls

### ISSUE THREAD

**Issue by jorgebucaran** [ai/nanocolors#17]
nanocolors is bleeding styles inside nested calls, I think it only happens with `dim` and `bold`, which are weird.

<img width="915" alt="Screen Shot 2021-09-26 at 7 12 37" src="https://user-images.githubusercontent.com/56996/134787148-4089252e-d9a3-4dc5-9172-b88b1c5f4c2e.png">

Problem should be here:

https://github.com/ai/nanocolors/blob/b268858abb91f86dfbbd1aa90f261f5364bdd02b/index.js#L51-L52

If you pass the replace regex to your internal `color` function you should be set, [like this](https://github.com/jorgebucaran/colorette/blob/02d2141da4dbfdc83992c25e7a7d80c3c2694a0a/index.js#L38-L39).

**Comment by ai** [comment]
Fixed 665cf07
