### ISSUE TITLE
Benchmark result needs updating

### ISSUE THREAD

**Issue by jorgebucaran** [ai/nanocolors#18]
Just released Colorette [`2.0.11`](https://github.com/jorgebucaran/colorette/releases/tag/2.0.11) with further perf improvements. This is what I'm seeing in the CI.

- https://github.com/jorgebucaran/color-bench-test/runs/3710045880?check_suite_focus=true

<img width="1032" alt="Screen Shot 2021-09-26 at 7 58 34" src="https://user-images.githubusercontent.com/56996/134787984-80af342b-2ac2-4365-bc64-6fb1a0a27c45.png">

If you run your benchmarks in the CI you'd avoid copy & pasting from your terminal all the time.

Would be nice if you could update your README with these results (or remove outdated results).

**Comment by ai** [comment]
Done 05fabe0

I hope you will address my request of mentioning the author of this improvement https://github.com/jorgebucaran/colorette/issues/78
