### ISSUE TITLE
Way to disable colors manually via js?

### ISSUE THREAD

**Issue by daKmoR** [ai/nanocolors#25]
I like to do this in my test

```js
import chai from 'chai';
import { isColorSupported  } from 'nanocolors';
import { executeCli } from './test-helpers.js';

const { expect } = chai;

describe('cli', () => {
  before(() => {
    // ignore colors in tests as most CIs won't support it
    isColorSupported = false;
  });
```

which fails as you can't change variables you import?

maybe `isColorSupported` should be an object? 

or is there another way to disable it while running the test locally that does not require a cli flag?

**Comment by ai** [comment]
Sorry, there is no such API.

I have `no-colors.js` with `process.env.NO_COLOR = '1'` and import it before importing a tool.

**Comment by TrySound** [comment]
Or you can pass --no-color flag to your command if executed with child_process.

**Comment by daKmoR** [comment]
fair enough
