### ISSUE TITLE
Add template API

### ISSUE THREAD

**Issue by ai** [ai/nanocolors#6]
People like chalk’s template API a lot. We need to find a way to copy it in a form:

```js
import { colorize } from 'nanocolors'

colorize`CPU: {red ${cpu.totalPercent}%}`
```

**Comment by suxin2017** [comment]
Maybe try something like this?
```javascript
colorize('CPU: %red ',cup.totalPercent)
colorize('CPU: %red_bold ',cup.totalPercent)
colorize('CPU: %red_bold_bgRed ',cup.totalPercent)
```

**Comment by ai** [comment]
People will need also to colorize a static text like:

```
colorize`Usage: cli-tool {yellow FILE}`
```

**Comment by suxin2017** [comment]
![image](https://user-images.githubusercontent.com/28481035/134616359-a4776b75-3ba3-496f-aaea-3c20eda97f84.png)
I wrote a demo of that

**Comment by usmanyunusov** [comment]
nanocolors-template - https://github.com/usmanyunusov/nanocolors-template
