### ISSUE TITLE
Add Deno support

### ISSUE THREAD

**Issue by ai** [ai/nanocolors#8]
We need a separated file excluded from npm package and using `deno.noColor`.

What hosting should we use to server ESM file?

**Comment by alexeyten** [comment]
What about https://deno.land/x ?

**Comment by ai** [comment]
Thanks. I took the name and will add Deno file with guide in docs tomorrow.

**Comment by ai** [comment]
Fixed https://github.com/ai/nanocolors/commit/5452c035979e3227a6ffc550192eb8708347192b

**Comment by alexeyten** [comment]
It’s gone now? Why so?

**Comment by ai** [comment]
Because Deno has color functions in stdlib.
