### ISSUE TITLE
Publish an ES module

### ISSUE THREAD

**Issue by 43081j** [ai/nanocolors#9]
`index.browser.js` wouldn't actually work in a browser since its a commonjs module.

what'd be really nice is to replace this with an ES module (`"module": "ES2020"` for example when running `tsc`).

then we would be able to load the module directly in browsers, deno, node ESM, etc.

though you may need to add an `exports` field in your package.json to make node detect it properly:

```json
  "exports": {
    "import": "./index.browser.js",
    "require": "./index.js"
  },
```

**Comment by 43081j** [comment]
aha so you do!

https://unpkg.com/browse/nanocolors@0.1.6/index.browser.js

in actual fact you also have an `exports` field, i guess that is also generated at publish time.

the docs are probably fine, you already mention ESM support but i didn't notice that, my bad :+1:

**Comment by ai** [comment]
Hope link will make “ESM” more visible
